version: '3.8'

services:
  postresql:
    image: postgres:latest
    container_name: postgres_ws
    restart: always
    environment:
      POSTGRES_PASSWORD: admin@123
      POSTGRES_USER: admin
      POSTGRES_DB: lanchonete_ws
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  lanchonetews:
    image: wstecnologia/lanchonetews:v1.0
    restart: always
    ports:
      - 3000:3000
    environment:
      WS_DB_HOST: postresql
      WS_DB_USER: admin
      WS_DB_PASSWORD: admin@123
      WS_DB_NAME: lanchonete_ws
    depends_on:
      - postresql
